### ISSUE TITLE
Need some help...

### ISSUE THREAD

**Issue by Altify-Development** [tj-actions/puppeteer#87]
To the devs,

<p>&nbsp;&nbsp;&nbsp;So, I am rather new to the world of github actions, but I have been prospecting for a chance to make a GitHub 3rd party website analysis and a tool that can suggest and automatically make improvements to a project. So far, I have been able to make verified commits and machine learning to suggest, but I am looking for a way to anonymously view a github repository using chromeheadless, this is where you come in. With your knowledge, you can potentially solve my problem of display fragmentation and make it possible for my idea to come to life.</p>

<strong>EDIT</strong>
<p>the image is the link to the repository</p>
<a href="https://github.com/Altify-Developing/Altify-Developing-Main">
  <img src="https://github.com/Altify-Developing/Altify-Developing-Main/raw/main/img/logo-main.png">
</a>

Kind regards,

CEO @ Altify Developing, LLC

Message from:
[Altify-Personal](https://github.com/Altify-Development)
[Altify-Organization](https://github.com/Altify-Developing)
<p>&copy; Altify Developing 2022</p>

**Comment by jackton1** [comment]
@Altify-Development I’ll like to know if this is a job opportunity and if so what are the specifics in terms of what your hoping to archive with AltifyMarketing project

**Comment by Altify-Development** [comment]
> @Altify-Development I’ll like to know if this is a job opportunity and if so what are the specifics in terms of what are you hoping to archive with Altify project

Glad you asked, this is a partnership offering. Also, the project is a forever growing list of ideas that would be very much illegal if not used correctly, and some shouldn't be created at all, but I like to create them because it is my passion. Following that, this tool that I am making is a tool that can make a website and its sub-sites crawled, and popularized with the help of you. It would also hopefully mean that you are able to collaborate on more of my ideas.

P.S.
I will give you credit obviously but I just wanted to make sure that was in there. Also, the contents of the repository are constantly changing, so it may be completely different by the time you see it again.

**Comment by Altify-Development** [comment]
@jackton1

**Comment by jackton1** [comment]
Okay, we’ll as good as the proposition sounds. I’m quite busy ATM and I only contribute to projects with financial backing.
